version: '2'
services:
    newtesttest-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/newTestTest/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=newTestTest
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
